INSERT INTO product_categories (name)
VALUES 
    ('Elektronik'),
    ('Kecantikan'),
    ('Kesehatan'),
    ('Gaming'),
    ('Fashion'),
    ('Film & Alat Musik'),
    ('Handphone & Tablet'),
    ('Mainan'),
    ('Komputer & Laptop'),
    ('Office'),
    ('Olahraga'),
    ('Wedding'),
    ('Tiket Travel'),
    ('Dapur'),
    ('Logam Mulia'),
    ('Otomotif'),
    ('Perawatan'),
    ('Perawatan Hewan');
