INSERT INTO products (name, description, price, quantity)
VALUES 
  ('Mesin Hitung dan Deteksi Uang Kertas Rupiah Cashtek ST-8090 (2 Pocket)', 'Sudah dapat membaca dan mendeteksi uang Rupiah terbaru. Dapat mendeteksi asli/palsu, membedakan/membaca, dan memisahkan pecahan uang yang dihitung. Juga dapat merapikan uang yang terbalik-balik.', 16980000, 10),
  ('Cypruz Grey Marble Fry Pan / Wajan Penggorengan Anti Lengket - 22 cm', 'CYPRUZ GREY MARBLE, WAJAN KEKINIAN DENGAN KUALITAS PREMIUM.', 162000, 7),
  ('BNB barenbliss Cherry Makes Cheerful Lip Velvet - 24H Moisture - 11 Coral Bloom', 'Lip velvet bertekstur mousse dengan aroma buah ceri menyegarkan yang mengandung Macadamia Organic Oil, Vitamin E, dan Hyaluronic Acid untuk bibir yang tetap kenyal dan sehat.', 55000, 14),
  ('[Twin Pack Mist] Azarine Hydrasoothe Sunscreen Mist SPF50 PA++++ 60ml', 'Tabir surya spray yang praktis. Di formulasikan “water based” dengan gabungan bahan aktif Hyaluronic Acid, Ceramide dan CICA pada kulit serta melembabkan agar kulit kenyal dan halus', 102699, 25),
  ('Bundle 2x 550ml Eucalyptus & Lavender Air Disinfectant Spray - NORVUS', 'Air Disinfectant Spray / Disinfektan Spray sekaligus pengharum ruangan yang mampu membunuh kuman, bakteri dan jamur serta virus.', 50000, 5),
  ('Mesin PS5 Console Digital Version Final Fantasy XVI / FF 16 (SONY INDO)', 'Mesin Seal Original Hologram & Garansi Resmi Warranty 1+1 Sony Indonesia', 8778000, 5),
  ('Jam Tangan Pria Seiko 5 Sports SRPD55K1 Automatic Black Dial SRPD55', 'Movement Caliber Number 4R36 Duration:Approx. 41 hours', 3520820, 60),
  ('Ukulele Concert Mandalika Coklat Tua Original Concerto Full Set', 'Ukulele Mandalika Premium Brand Original From Indonesia, Concerto berukuran 23inci 4 Senar Nylon', 350000, 813),
  ('Samsung Galaxy A04S 4/64 Garansi Resmi - Flash Black', 'Samsung Galaxy A04S 4/64 Original Garansi Resmi', 1999000, 1281),
  ('KKV - Mainan Brick Susun Balok Mobil SEMBO Iron Blood-VT-4 Battle Tank', 'KKV - Mainan Brick Susun Balok Mobil SEMBO Iron Blood-VT-4 Battle Tank. Senbao Building Blocks merupakan mainan edukasi untuk anak-anak yang bertujuan melatih tingkat konsentrasi dan fokus.', 67900, 46),
  ('MSI Titan GT77HX 13VI i9-13980HX RTX4090 17.3" UHD Mini LED HDR 1000', 'MSI Titan GT77HX 13VI-263ID. Beyond Fast with GeForce RTX 40 Series', 89999000, 91),
  ('PaperOne Kertas A4 80gr All Purpose 1 Box (2500 lembar) Kertas HVS', 'Ramah lingkungan 100% berbahan serat dari perkebunan bersertifikat PEFC', 252700, 60),
  ('Terlarisss MEWAH MURAH BANGET SEPASANG KEBAYA PENGANTIN EKOR', 'Material: Satin- Tille', 1520000, 5),
  ('UMROH AKHIR TAHUN', 'MROH MURAH HOTEL DEKAT DAFTAR SEKALI UMROH 3 KALI', 33000000, 100),
  ('Keeo 16 cm Wajan Penggorengan Anti Lengket Marble Granit Pink', 'Gagang dari Bakelite Soft Touch, AMAN, tidak mudah terbakar dan tidak licin', 69900, 3803),
  ('LOGAM MULIA, LM ANTAM, EMAS BATANGAN KEPINGAN 5 GRAM', 'LM ANTAM 5 GRAM KEMASAN REINVENTED 2023', 5390000, 878),
  ('Sarung Mobil / Cover Mobil Plastik Transparan Tebal Waterproof M Size - XL', 'Material: Plastik PE 40 micron Waterproof/Sunproof/Dustproof', 128000, 227),
  ('Kahf Complete Body Wash Pack 200 ml x 2 pcs', 'Kahf Brightening and Cooling Body Wash 200 ml, Kahf Acne Fight and Relaxing Body Wash 200 ml', 48420, 10),
  ('PAW POWER Tofu Cat Litter Fast Clumping 7L - Pasir Kucing Gumpal Soya - Trial Size 1Kg, Original (Milk)', 'Pawparents kini tidak perlu repot lagi membersihkan kotoran anabul atau khawatir terhadap lingkungan rumah menjadi tidak higienis dengan hadirnya Paw Power Tofu Cat Litter sebagai inovasi pasir soya', 34900, 11),
  ('ONLY PETS Puffy Pet Collar Cone Bantal Pelindung Leher Lucu - Peach S', 'Pet collar ini merupakan bantalan pelindung yang bisa digunakan pada leher hewan kesayangan anda. Corong ini digunakan agar hewan tidak menjilati/mengigit bagian tubuh mereka', 89900, 24);
